version: "3.8"

services:
  backend:
    build: ./backend
    env_file:
      - .env
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - backend